# Generated by Django 5.1.2 on 2024-10-21 06:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringorder',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cateringorder',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='cateringorder',
            name='menu_details',
        ),
        migrations.RemoveField(
            model_name='cateringorder',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cateringorder',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='eventplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='eventplan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='staffschedule',
            name='assigned_order',
        ),
        migrations.RemoveField(
            model_name='staffschedule',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staffschedule',
            name='shift_date',
        ),
        migrations.RemoveField(
            model_name='staffschedule',
            name='shift_time',
        ),
        migrations.RemoveField(
            model_name='staffschedule',
            name='staff_name',
        ),
        migrations.RemoveField(
            model_name='staffschedule',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cateringorder',
            name='menu_items',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cateringorder',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='cateringorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cateringorder',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventplan',
            name='event_status',
            field=models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Planned', max_length=50),
        ),
        migrations.AddField(
            model_name='eventplan',
            name='number_of_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventplan',
            name='resources_needed',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='assigned_event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='carters.eventplan'),
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='shift_end',
            field=models.TimeField(default='17:00:00'),
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='shift_start',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AddField(
            model_name='staffschedule',
            name='staff_member',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cateringorder',
            name='client_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cateringorder',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='event_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
